### ISSUE TITLE
Error: '#193 %1 is not a valid Win32 application'  on Appveyor

### ISSUE THREAD

**Issue by uribo** [uribo/textlintr#5]
Appveyor上のテストで`init_textlintr()` を実行すると次のエラーになる。

https://ci.appveyor.com/project/uribo/textlintr/build/1.0.10#L441

権限周りのエラーのようで、今の所解決策がわからない。

**Comment by niszet** [comment]
Windows環境で使用しているので挙動のご報告。
`init_textlintr()`を実行してもエラーにはなりませんが、インストールはされずに`textlint()`実行時に下記のようにエラーになります。こちらでも調べてみます。

```r
textlintr::init_textlintr()
textlint(lint_target)
## Error in process_initialize(self, private, command, args, stdin, stdout,  : 
##   Command not found
```

**Comment by niszet** [comment]
上記の挙動ですが、どうもglobalのnpmパッケージとしてtextlintを私がインストールしていたためらしく、一旦`npm uninstall textlint -g`したところ、

```r
textlintr::init_textlintr()
Yeah! Install was successful
```
とインストールでき、無事に

```
 Error in process_initialize(self, private, command, args, stdin, stdout,  : 
  processx error, create process: #193 %1 は有効な Win32 アプリケーションではありません。
 at 'win/processx.c:1039' 
```
が再現できました。確認していきます。

**Comment by uribo** [comment]
報告ありがとうございます。

はい、現在の仕様では`init_textlintr()` の実行で `.textlintr/` ディレクトリの中に`package.json`を作成し、そこで`npm install` を行うようになっています（textlintおよびルール用のファイルがインストールされます）。

READMEの情報が誤っていますね。すみません、訂正しておきます (#12)。

**Comment by niszet** [comment]
globalの方にインストールしていても、`is_installed_dependencies("textlint")`が`TRUE`を返しているようなので、`.textlintr/`に依存するコードがあるとそこでエラーになる…かも？今のところ問題ないですが。

本件、下記のエラーメッセージと同じなのですが、現象的にはちょっと違いそう…。実行pathには空白文字は入っていないので…。
https://support.microsoft.com/en-us/help/812486/event-id-7000-and-1-is-not-a-valid-win32-application-error-message-whe

こちらの、executableではない云々の方が気になりますね。
http://forums.codeguru.com/showthread.php?532247-error-193-with-CreateProcess-why

.js自体はwin上では単体では実行できない気がするので…もう少し調べてみます。

**Comment by uribo** [comment]
`Sys.which("textlint")` の結果はどうなりますか？

**Comment by niszet** [comment]
こんな感じです。おや…？調べてみます。

```r
> Sys.which("textlint")
textlint 
      "" 
```

**Comment by uribo** [comment]
ありがとうございます。一度textlintはアンインストールされているのですよね (https://github.com/uribo/textlintr/issues/5#issuecomment-428950894)

エラー処理が不十分で、`init_textlintr() `で正常終了しても`npm install`が成功していない可能性があります。

https://github.com/uribo/textlintr/blob/2e61001b32ff0088daf79a6c9edfd0bea3ca9a0b/R/textlintrc.R#L40-L47

**Comment by uribo** [comment]
こちらの問題はこのissueと違うと思うので、 続きは #15 で議論しましょう :)
